spring:
  datasource:
    url: mysql://root:UImkBbwPm9kRvGAdDKU6@containers-us-west-127.railway.app:5540/railway
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: bezishodnost
